# Generated by Django 3.2.4 on 2021-07-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tress_unlocked',
        ),
        migrations.AddField(
            model_name='user',
            name='tress_unlocked',
            field=models.ManyToManyField(to='api.Tree'),
        ),
    ]
