# Generated by Django 3.2.4 on 2021-07-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
